baseURL = 'https://minions-wiki.pages.dev/'
languageCode = 'en'
theme = 'hugo-cards'

# github pages
publishDir = "docs"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[pagination]
  pagerSize = 6

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Minions Wiki'
    weight = 1
  [languages.zh-cn]
    contentDir = 'content/zh-cn'
    disabled = false
    languageCode = 'zh-Hans'
    languageDirection = 'ltr'
    languageName = '简体中文-大陆'
    title = '小黄人百科'
    weight = 1
  [languages.zh-hk]
    contentDir = 'content/zh-hk'
    disabled = false
    languageCode = 'zh-Hant'
    languageDirection = 'ltr'
    languageName = '繁体中文-香港'
    title = '迷你兵團百科'
    weight = 1


[params]
  builtBy = "kugarocks"
  defaultImage = "minions-default.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/kugarocks/minions-wiki"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""
  
  custom_css = ["css/custom.css"]

  #[params.post.meta]
  #  isHidden = true

  [params.post.sidebar]
    type = "profile"
    title = "Profile"

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "Illumination Entertainment"
     link = "https://www.illumination.com/"