name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Listen for changes on the main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch all submodules
        fetch-depth: 0    # Fetch all history for proper submodule fetching

    # Setup Hugo Extended version
    # Ensure that the Hugo Extended version is used
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.134.2'
        extended: true

    # Build the Hugo site, output to the gh-pages directory
    - name: Build Hugo site to gh-pages
      run: hugo --baseURL="https://www.minions.wiki/" -d ./gh-pages

    # Add custom domain
    - name: Add CNAME file
      run: echo "www.minions.wiki" > ./gh-pages/CNAME

    # Deploy the contents of the gh-pages directory
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages

    # Build the Hugo site, output to the cf-pages directory
    - name: Build Hugo site to cf-pages
      run: hugo --baseURL="https://www.minion.wiki/" -d ./cf-pages

    # Deploy the contents of the cf-pages directory
    - name: Deploy to Cloudflare Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cf-pages
        publish_branch: cf-pages


